version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        uid: ${UID}
    container_name: easset
    restart: always
    labels:
      - traefik.backend=easset
      - traefik.frontend.rule=Host:e-asset.techack.id
      - traefik.docker.network=web
      - traefik.port=80
    volumes:
      - ./src:/var/www/html/src
    networks:
      - web
networks:
  web:
    external: true
volumes:
  src: